/**
----------------------------------------------------------
Author: Mayank Mehra
Date: Wednesday August 5, 2020
Purpose: GUI Change Exchange
----------------------------------------------------------
Description of code : Create an application that calculates how much a inputed 
dollar amount can be exchanged for in change
Description of update : Toonies and Loonies were added into the change 
exchange and the names of the variables were put into proper camel formating
--------------------------------------------------------
 */

package ChangeCalculator;

public class ChangeCalculator extends javax.swing.JFrame {

    /**
     * Creates new form ChangeApp
     */
    public ChangeCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQuarters1 = new javax.swing.JTextField();
        lblChangeExchangeTitle = new javax.swing.JLabel();
        lblEnterCurrency = new javax.swing.JLabel();
        lblAmountUnderCurrency = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtCurrency = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblQuarters = new javax.swing.JLabel();
        lblDimes = new javax.swing.JLabel();
        lblNickels = new javax.swing.JLabel();
        lblPennies = new javax.swing.JLabel();
        txtQuarters = new javax.swing.JTextField();
        txtNickels = new javax.swing.JTextField();
        txtDimes = new javax.swing.JTextField();
        txtPennies = new javax.swing.JTextField();
        lblLoonies = new javax.swing.JLabel();
        lblToonies = new javax.swing.JLabel();
        txtLoonies = new javax.swing.JTextField();
        txtToonies = new javax.swing.JTextField();

        txtQuarters1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblChangeExchangeTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblChangeExchangeTitle.setForeground(new java.awt.Color(255, 0, 102));
        lblChangeExchangeTitle.setText("Change Exchange");

        lblEnterCurrency.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEnterCurrency.setText("Enter Currency");

        lblAmountUnderCurrency.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAmountUnderCurrency.setText("Amount (xxxx.xx)");

        btnCalculate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtCurrency.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAmount.setText("Amount");

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblQuarters.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuarters.setText("Quarters");

        lblDimes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDimes.setText("Dimes");

        lblNickels.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNickels.setText("Nickels");

        lblPennies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPennies.setText("Pennies");

        txtQuarters.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNickels.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDimes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPennies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPennies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenniesActionPerformed(evt);
            }
        });

        lblLoonies.setText("Loonies");

        lblToonies.setText("Toonies");

        txtLoonies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLooniesActionPerformed(evt);
            }
        });

        txtToonies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTooniesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPennies)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPennies, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNickels)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtNickels, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblToonies)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtToonies))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLoonies)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLoonies, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblAmountUnderCurrency)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEnterCurrency)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblAmount)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblDimes)
                                                    .addGap(16, 16, 16)))
                                            .addComponent(lblQuarters))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDimes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnCalculate))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(lblChangeExchangeTitle)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblChangeExchangeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterCurrency)
                    .addComponent(txtCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAmountUnderCurrency)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuarters)
                    .addComponent(lblNickels)
                    .addComponent(txtQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNickels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoonies)
                    .addComponent(txtLoonies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDimes)
                    .addComponent(lblPennies)
                    .addComponent(txtDimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPennies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToonies)
                    .addComponent(txtToonies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); // Exit the application.
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        
        //declaring varibales
        String strAmountIn; // the currency
        int intTotal, intToonies, intLoonies, intQuarters, intDimes, intNickels, intPennies;
        double dblConvertIn;

        strAmountIn = txtCurrency.getText();
        // Convert the amount from $ to cents.
        dblConvertIn = Double.parseDouble(strAmountIn) * 100;
        // Truncate all the decimals that come after cents.
        intTotal = (int)dblConvertIn;
        
        //Calculate the number of toonies. 
        intToonies  = intTotal / 200; 
        intTotal = intTotal - (intToonies * 200); 
        //Calculate the numbe of loonies
        intLoonies = intTotal / 100;
        intTotal = intTotal - (intLoonies * 100); 
        // Calculate the number of quarters.
        intQuarters = intTotal / 25;
        intTotal = intTotal - (intQuarters * 25);
        // Calculate the number of dimes.
        intDimes = intTotal / 10;        
        intTotal = intTotal - (intDimes * 10);
        // Calculate the number of nickels.
        intNickels = intTotal / 5;
        intTotal = intTotal - (intNickels * 5);
        // Calculate the number of pennies.
        intPennies = intTotal;

        
        // Output the input amount.
        txtAmount.setText(strAmountIn);
        //Output the number of toonies.
        txtToonies.setText(Integer.toString(intToonies));
        //Output the number of loonies.
        txtLoonies.setText(Integer.toString(intLoonies)); 
        // Output the number of quarters.
        txtQuarters.setText(Integer.toString(intQuarters));
        // Output the number of dimes.
        txtDimes.setText(Integer.toString(intDimes));
        // Output the number of nickels.
        txtNickels.setText(Integer.toString(intNickels));
        // Output the number of pennies.
        txtPennies.setText(Integer.toString(intPennies));
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtLooniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLooniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLooniesActionPerformed

    private void txtPenniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenniesActionPerformed

    private void txtTooniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTooniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTooniesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmountUnderCurrency;
    private javax.swing.JLabel lblChangeExchangeTitle;
    private javax.swing.JLabel lblDimes;
    private javax.swing.JLabel lblEnterCurrency;
    private javax.swing.JLabel lblLoonies;
    private javax.swing.JLabel lblNickels;
    private javax.swing.JLabel lblPennies;
    private javax.swing.JLabel lblQuarters;
    private javax.swing.JLabel lblToonies;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCurrency;
    private javax.swing.JTextField txtDimes;
    private javax.swing.JTextField txtLoonies;
    private javax.swing.JTextField txtNickels;
    private javax.swing.JTextField txtPennies;
    private javax.swing.JTextField txtQuarters;
    private javax.swing.JTextField txtQuarters1;
    private javax.swing.JTextField txtToonies;
    // End of variables declaration//GEN-END:variables
}
