package AirlinePointsProgram;

import java.util.ArrayList; 

/**
----------------------------------------------------------
Author: Mayank Mehra
Date: Saturday August 16, 2020
Purpose: AirLine Points Program
----------------------------------------------------------
Description of code : Program will save users name and weekly points and will 
display their total airline points and whether they qualified for the bonus points
--------------------------------------------------------
 */

public class AirLinePointProgram extends javax.swing.JFrame {
    
    //declare a global passanger data class arraylist that will save input
    ArrayList <passangerData> arrPassangerData = new ArrayList <passangerData> (); 
    
    
    /**
     * Creates a class for each person entered and save their data in a class arraylist
     */
    class passangerData {
        String strFirstName, strLastName; 
        int intWeek1, intWeek2, intWeek3, intWeek4;
        
        /**
         * Defines the attributes of the passangerData class 
         * @param strTempFirst takes in user first name 
         * @param strTempLast takes in user last name 
         * @param intTemp1 week 1 points 
         * @param intTemp2 week 2 points 
         * @param intTemp3 week 3 points 
         * @param intTemp4 week4 points
         */
        passangerData(String strTempFirst, String strTempLast, int intTemp1, int intTemp2, int intTemp3, int intTemp4) {
            
            strFirstName = strTempFirst; 
            strLastName = strTempLast; 
            intWeek1 = intTemp1; 
            intWeek2 = intTemp2; 
            intWeek3 = intTemp3; 
            intWeek4 = intTemp4; 
            
        }
    }
    
    /**
     * Clears all the textfields and text area
     */
    public void clearTextField () {
        
        txtAOutput.setText(null);
        txtFirstName.setText(null);
        txtLastName.setText(null);
        txtWeek1.setText(null);
        txtWeek2.setText(null);
        txtWeek3.setText(null);
        txtWeek4.setText(null);
        
    }
    
    public AirLinePointProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblWeek1 = new javax.swing.JLabel();
        txtWeek1 = new javax.swing.JTextField();
        lblWeek2 = new javax.swing.JLabel();
        txtWeek2 = new javax.swing.JTextField();
        lblWeek3 = new javax.swing.JLabel();
        txtWeek3 = new javax.swing.JTextField();
        lblWeek4 = new javax.swing.JLabel();
        txtWeek4 = new javax.swing.JTextField();
        scrollOutput = new javax.swing.JScrollPane();
        txtAOutput = new javax.swing.JTextArea();
        seperatorDesign = new javax.swing.JSeparator();
        btnExit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnTotalPoints = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelBackground.setBackground(new java.awt.Color(204, 255, 255));
        panelBackground.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Airline Points");
        panelBackground.add(lblTitle);
        lblTitle.setBounds(0, 0, 590, 58);

        txtFirstName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        panelBackground.add(txtFirstName);
        txtFirstName.setBounds(140, 70, 140, 40);

        lblLastName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblLastName.setText("Last Name:");
        panelBackground.add(lblLastName);
        lblLastName.setBounds(310, 80, 110, 20);

        txtLastName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        panelBackground.add(txtLastName);
        txtLastName.setBounds(420, 70, 140, 40);

        lblFirstName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblFirstName.setText("First Name: ");
        panelBackground.add(lblFirstName);
        lblFirstName.setBounds(30, 80, 110, 22);

        lblWeek1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblWeek1.setText("Week 1:");
        panelBackground.add(lblWeek1);
        lblWeek1.setBounds(30, 140, 80, 22);

        txtWeek1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        panelBackground.add(txtWeek1);
        txtWeek1.setBounds(120, 130, 170, 40);

        lblWeek2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblWeek2.setText("Weeks 2:");
        panelBackground.add(lblWeek2);
        lblWeek2.setBounds(30, 190, 90, 22);

        txtWeek2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        panelBackground.add(txtWeek2);
        txtWeek2.setBounds(120, 180, 170, 40);

        lblWeek3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblWeek3.setText("Weeks 3:");
        panelBackground.add(lblWeek3);
        lblWeek3.setBounds(30, 240, 90, 22);

        txtWeek3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        panelBackground.add(txtWeek3);
        txtWeek3.setBounds(120, 230, 170, 40);

        lblWeek4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblWeek4.setText("Weeks 4:");
        panelBackground.add(lblWeek4);
        lblWeek4.setBounds(30, 290, 90, 22);

        txtWeek4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        panelBackground.add(txtWeek4);
        txtWeek4.setBounds(120, 280, 170, 40);

        txtAOutput.setColumns(20);
        txtAOutput.setRows(5);
        scrollOutput.setViewportView(txtAOutput);

        panelBackground.add(scrollOutput);
        scrollOutput.setBounds(30, 340, 520, 260);

        seperatorDesign.setForeground(new java.awt.Color(0, 0, 0));
        panelBackground.add(seperatorDesign);
        seperatorDesign.setBounds(0, 600, 600, 10);

        btnExit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelBackground.add(btnExit);
        btnExit.setBounds(450, 610, 130, 40);

        btnAdd.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelBackground.add(btnAdd);
        btnAdd.setBounds(390, 140, 130, 40);

        btnList.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        panelBackground.add(btnList);
        btnList.setBounds(390, 200, 130, 40);

        btnTotalPoints.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnTotalPoints.setText("Total Points");
        btnTotalPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPointsActionPerformed(evt);
            }
        });
        panelBackground.add(btnTotalPoints);
        btnTotalPoints.setBounds(390, 260, 130, 40);

        getContentPane().add(panelBackground);
        panelBackground.setBounds(0, 0, 590, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        //gets user input
        String strFirstName = txtFirstName.getText(); 
        String strLastName = txtLastName.getText(); 
        
        int intWeek1 = Integer.parseInt(txtWeek1.getText()); 
        int intWeek2 = Integer.parseInt(txtWeek2.getText());
        int intWeek3 = Integer.parseInt(txtWeek3.getText());
        int intWeek4 = Integer.parseInt(txtWeek4.getText());
        
        //clears all text fields
        clearTextField(); 
        
        //creates a new instance of the passanger data class that is then saved in the arraylist
        passangerData tempPData = new passangerData(strFirstName, strLastName, intWeek1, intWeek2, intWeek3, intWeek4);
        arrPassangerData.add(tempPData); 
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        
        //clear text fields 
        clearTextField(); 
        
        //runs through all the attributes for each instance of the passangerData class in the arraylist and outputs it in textarea
        for (int i = 0; i < arrPassangerData.size(); i++) {
            txtAOutput.append(arrPassangerData.get(i).strFirstName + " " 
                    + arrPassangerData.get(i).strLastName + " " 
                    + arrPassangerData.get(i).intWeek1 + " " 
                    + arrPassangerData.get(i).intWeek2 + " "
                    + arrPassangerData.get(i).intWeek3 + " "
                    + arrPassangerData.get(i).intWeek4 + " "
                    + "\n");
        }
        
    }//GEN-LAST:event_btnListActionPerformed

    private void btnTotalPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPointsActionPerformed
        
        //gets user input
        String strFirstName = txtFirstName.getText(); 
        String strLastName = txtLastName.getText(); 
        
        //clears text fields
        clearTextField(); 
        
        int intTotal = 0; 
        int intBonus = 0; 
        
        //loops through arraylist and checks if first and last name inputed by user exists
        for (int i = 0; i < arrPassangerData.size(); i++) {
            if (strFirstName.equals(arrPassangerData.get(i).strFirstName) && strLastName.equals(arrPassangerData.get(i).strLastName) ) {
                //uses i as the index value of where the name appears and adds up the points for that user 
                intTotal += arrPassangerData.get(i).intWeek1;
                intTotal += arrPassangerData.get(i).intWeek2;
                intTotal += arrPassangerData.get(i).intWeek3;
                intTotal += arrPassangerData.get(i).intWeek4;
            }
        }
        //saves int bonus as 1000 if the user has more then 5000 points 
        if (intTotal > 5000) intBonus = 1000; 
        
        //outputs info 
        txtAOutput.setText(strFirstName + " " + strLastName + "'s Total Points are: "
                           + intTotal + "\nBonus: " + intBonus); 
        
    }//GEN-LAST:event_btnTotalPointsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       
        //closes gui window and program
        System.exit(0); 
        
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirLinePointProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirLinePointProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirLinePointProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirLinePointProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirLinePointProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnTotalPoints;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWeek1;
    private javax.swing.JLabel lblWeek2;
    private javax.swing.JLabel lblWeek3;
    private javax.swing.JLabel lblWeek4;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JScrollPane scrollOutput;
    private javax.swing.JSeparator seperatorDesign;
    private javax.swing.JTextArea txtAOutput;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtWeek1;
    private javax.swing.JTextField txtWeek2;
    private javax.swing.JTextField txtWeek3;
    private javax.swing.JTextField txtWeek4;
    // End of variables declaration//GEN-END:variables
}
